# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 02:55
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(blank=True, max_length=10, null=True)),
                ('unit_no', models.CharField(blank=True, max_length=20, null=True)),
                ('isn', models.CharField(max_length=20, null=True, verbose_name='ISN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Devices',
                'verbose_name': 'Device',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(help_text='只接受英文、數字、半形符號.內容作為信件標題請仔細填寫 (限制字數三百字). ', max_length=300, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Chinese characters are restricted. Must be alphanumeric(只接受英文、數字、半形符號).', regex='^[a-z A-Z 0-9 \\[^\\u4e00-\\u9fa5\\] /,.?~!@#$%^&*()_+]*$')], verbose_name='Loan Purpose')),
                ('pega_dri_mail_group', models.CharField(max_length=600, null=True, verbose_name='Pega DRI Mail Group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cocodri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cocodri_item', to='users.Cocodri', verbose_name='CoCo DRI')),
                ('function_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Functionteam', verbose_name='Function Team')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_loans', to=settings.AUTH_USER_MODEL)),
                ('pegadri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pegadri_item', to='users.Pegadri', verbose_name='Pega DRI')),
            ],
            options={
                'verbose_name_plural': 'Loans',
                'verbose_name': 'Loan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='loans.Loan', verbose_name='loan'),
        ),
    ]
